#spring.application.name=myevent-be


server:
  port: 8080
  servlet:
    context-path: /event-management

spring:
  datasource:
    url: jdbc:sqlserver://localhost:31622;databaseName=event-management4;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driverClassName: com.mssql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngohuyen.280703@gmail.com
    password: khanhhuyen28072003
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: "qqziwod2yMQH8iDEZ/893gnzz4KtX4YDKnJz7OuQ/rSjdRssiWWtynVHhmERdhs7"
  valid-duration: 20 #in second
  refreshable-duration: 120 # in seconds